name: Crawl Amazon best sellers & update sheet

on:
  schedule:
    - cron: '0 21 * * *'     # 매일 06:00 KST (UTC 21:00)
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Playwright binaries   # ✅ 캐시 블록은 독립된 step
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run crawler
        env:
          SHEET_ID:      ${{ secrets.SHEET_ID }}
          GCP_SA_BASE64: ${{ secrets.GCP_SA_BASE64 }}
        run: python crawl.py
