name: Crawl Amazon best sellers & update sheet

on:
  schedule:
    - cron: '0 21 * * *'   # 매일 06:00 KST (UTC 21:00)
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Run crawler
        env:
          SHEET_ID:        ${{ secrets.SHEET_ID }}
          GCP_SA_BASE64:   ${{ secrets.GCP_SA_BASE64 }}
        run: python crawl.py
      - name: Upload debug_dump.html
        if: always()              # 실패해도 업로드
        uses: actions/upload-artifact@v4
        with:
          name: debug_dump
          path: /tmp/debug_dump.html
          retention-days: 3       # 필요 기간만큼
